from _NetworKit import AdamicAdarDistance, Diameter, Eccentricity, EffectiveDiameter, EffectiveDiameterApproximation, HopPlotApproximation, JaccardDistance, AlgebraicDistance, NeighborhoodFunction, NeighborhoodFunctionApproximation, CommuteTimeDistance, NeighborhoodFunctionHeuristic
from _NetworKit import _DiameterAlgo as DiameterAlgo
