import networkx as nx
import time
G = nx.read_gml('input/power.gml')
#G = nx.read_gml('input/PGPgiantcompo.gml')
#G = nx.read_gml('input/memplus.gml')
#G = nx.read_gml('input/cs4.gml')
#G = nx.read_gml('input/as-22july06.gml')
#G = nx.read_gml('input/bcsstk30.gml')
#G = nx.read_gml('input/cond-mat-2003.gml')
#G = nx.read_gml('input/rgg_n_2_15_s0.gml')
#G = nx.read_gml('input/fe_pwt.gml')
#G = nx.read_gml('input/cond-mat-2005.gml')
#G = nx.read_gml('input/delaunay_n16.gml')
#G = nx.read_gml('input/rgg_n_2_16_s0.gml')
#G = nx.read_gml('input/kron_g500-simple-logn16.gml')
#G = nx.read_gml('input/luxembourg.osm.gml')
#G = nx.read_gml('input/delaunay_n17.gml')
#G = nx.read_gml('input/citationCiteseer.gml')
#G = nx.read_gml('input/coPapersCiteseer.gml')
start = time.time()
nx.closeness_centrality(G, None, None, False)
print(time.time() - start)
